### ISSUE TITLE
Not able to get any output

### ISSUE THREAD

**Issue by Logan1x** [tea3/hexo-tag-twitter#1]
I am using the syntax given in readme.txt but not able to get my tweet. this is what comes when I use your plugin.
![image](https://user-images.githubusercontent.com/10944610/35471478-fbd7b990-0381-11e8-95f9-bb342df9bdff.png)

I am using icarus theme did you test on it.
and it would be lot better if you wrote demo post in english. Most people not able to understand a bit from it.

**Comment by tea3** [comment]
Please tell me the code of the article you wrote.

If the explanation is insufficient, I will update the readme.md

Sorry , I can't understand English almost. However, I will do as much as possible. Also , I'm happy that if you introduce in English how to use this plugin in your blog.

**Comment by Logan1x** [comment]
1.
> Please tell me the code of the article you wrote.

`{% twitter https://twitter.com/tea0828/status/819885806714138624 %}`

2.  I am using hexo blog with icarus theme.

**Comment by Logan1x** [comment]
when i installed plugin and paste the syntax in my markdown file i got [this](https://hexo.io/docs/troubleshooting.html#Template-render-error) error too but as soon as i removed the line from markdown it was resolved.

**Comment by tea3** [comment]
@Logan1x 

I tried to occur same problem. but it did'nt occur. The environment I tried is as follows.

- node.js: v9.4.0
- hexo: v3.4.4
- theme: icarus

```
$ nvm install v9.4.0
$ nvm use v9.4.0
$ npm install hexo-cli
$ hexo new hexo94
$ cd hexo94
$ npm uninstall hexo --save
$ npm install hexo@3.4.4 --save
$ npm install hexo-tag-twitter --save
$ git clone https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus
$ mv themes/icarus/_config.yml.example themes/icarus/_config.yml
```

Next , I inserted code as follows.

```
{% twitter https://twitter.com/tea0828/status/819885806714138624 %}
```

I inserted [this tweet](https://twitter.com/tea0828/status/819885806714138624).

![res2](https://user-images.githubusercontent.com/15667928/35489478-a36eba92-04da-11e8-813d-2fc9bd1df461.jpg)

It was displayed without any problem. Is there any influence of other plugins ?

![res](https://user-images.githubusercontent.com/15667928/35489479-a8ad4b22-04da-11e8-8306-4f768e18f7c5.jpg)

**Comment by Logan1x** [comment]
![selection_006](https://user-images.githubusercontent.com/10944610/35500178-98d58d24-04fb-11e8-9db9-3ee66a09e0eb.png)
I am receiving these warnings, is that fine?

**Comment by Logan1x** [comment]
>  Is there any influence of other plugins?

 how can I know if another plugin making influence?

**Comment by Logan1x** [comment]
I don't have `nvm` installed does that makes any problem?

**Comment by tea3** [comment]
@Logan1x 

> I am receiving these warnings, is that fine?

This plugin has no dependency package. So , this warning is irrelevant to the plugin.
https://github.com/tea3/hexo-tag-twitter/blob/master/package.json#L5


> I don't have nvm installed does that makes any problem?

It's no problem.

> how can I know if another plugin making influence?

The following methods are conceivable.

- Try disabling suspicious plugins. It is recommended to invalidate one by one.
- Please check if the html code in `your-article.html` inserted by the this plugin has been replaced .

https://github.com/tea3/hexo-tag-twitter/blob/master/index.js#L23

This plugin is a simple plugin that inserts code like the one above. For example, the following code is inserted by the plug-in.

```
<div class="twitter-wrapper">
  <blockquote class="twitter-tweet">
    <a href="https://twitter.com/tea0828/status/819885806714138624"></a>
  </blockquote>
</div>
<script async defer src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

There is a possibility that `widgets.js` file will be invalidated by other plugins.

```
<!-- Code may be converted by other plugins. -->
<div class="twitter-wrapper">
  <blockquote class="twitter-tweet">
    <a href="https://twitter.com/tea0828/status/819885806714138624"></a>
  </blockquote>
</div>
<!-- Is js file definitely inserted ? It may be invalidated by another plugin.  -->
<script async defer src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Please check the source code in your article. If there is no problem with the source code, other causes are conceivable.

## When it is normal

For example, the following helper tag `{% twitter https://twitter.com/tea0828/status/819885806714138624 %}` outputs code like the second image.

![res2](https://user-images.githubusercontent.com/15667928/35489478-a36eba92-04da-11e8-813d-2fc9bd1df461.jpg)

This code is equivalent to the output result of the helper tag.

![1](https://user-images.githubusercontent.com/15667928/35542046-4d8d44fa-05a1-11e8-93ff-dd3e57f5ce37.jpg)

If there is no problem, tweet will be displayed.

![res](https://user-images.githubusercontent.com/15667928/35489479-a8ad4b22-04da-11e8-8306-4f768e18f7c5.jpg)

## When it is problem

Let's reproduce the influence of other plugins.

![1-b](https://user-images.githubusercontent.com/15667928/35542054-574ea182-05a1-11e8-86c7-76913712e856.jpg)

It is the same as your results.

![2](https://user-images.githubusercontent.com/15667928/35542066-5ceafa32-05a1-11e8-9506-4b2b9aac6bd9.jpg)

![3](https://user-images.githubusercontent.com/15667928/35542069-6167ff7e-05a1-11e8-9812-0bdb637f5679.jpg)

**Comment by tea3** [comment]
@Logan1x 
Please check the source code.

**Comment by Logan1x** [comment]
Thanks a lot for helping I'll check this as soon as I can.
