### ISSUE TITLE
Dear Friend,Any way to change size for twitter tag?

### ISSUE THREAD

**Issue by JoeJoeyMa** [tea3/hexo-tag-twitter#2]
By the way, your blog is very beautiful, and the first sight is deeply attracted. Just when I was looking for tools for synchronous twitter expression, I saw your project. Though this tool could not synchronize twitter, but it was the first twitter to do in hexo. I'd like to ask how to adjust the size of the twitter introduction window. And the tools you use for your blog, and I'm very grateful if you can get a reply.
![tw](https://user-images.githubusercontent.com/20256976/37764677-43dae30c-2dfd-11e8-8180-8d573ea9daa2.png)

**Comment by tea3** [comment]
@JoeJoeyMa 
Thank you for seeing my site : )

As far as I can tell, the embedding of twitter seems to change size depending on the width of the parent element.  So I forcibly setting the width of the parent element with jquery.

However, the maximum width is 500 px. Do you want to enlarge to 500px or more ?

![1](https://user-images.githubusercontent.com/15667928/37769731-4a557c3e-2e15-11e8-824d-b157ada00f8d.jpg)
