### ISSUE TITLE
Center Tweets like the Instagram version.

### ISSUE THREAD

**Issue by kiarafbickers** [tea3/hexo-tag-twitter#3]
Could you center the tweet HTML and CSS like you did the `// generate html
 ` section of the Instagram version [here](https://github.com/tea3/hexo-tag-instagram/blob/master/index.js)?

**Comment by tea3** [comment]
@kiarafrobles  Yes , you can. This plugin can also be solved with similar css. Please replace [this code](https://github.com/tea3/hexo-tag-instagram/issues/3#issuecomment-335088688) with `.twitter-wrapper` .

**Comment by kiarafbickers** [comment]
That alone does not seem to center the widget.

**Comment by tea3** [comment]
@kiarafrobles Sorry , Could you solve by replacing [this code](https://github.com/tea3/hexo-tag-instagram/issues/3#issuecomment-335088688) with `.twitter-wrapper twitterwidget` ?

**Comment by kiarafrobles** [comment]
It works on mobile but not in my desktop browser for some reason. Link to post [here](http://kiararobles.com/blog/stop-posting-your-bitcoin-address-everywhere.html).

**Comment by kiarafbickers** [comment]
It works. Thank you!

**Comment by Boycottangent** [comment]
works for `.twitter-wrapper twitter-widget` not for `.twitter-wrapper twitterwidget`, a `-` mark is necessary.

**Comment by tea3** [comment]
@Boycottangent 
Your indication is correct. A `-` mark is necessary.
